language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/avodb

node_js:  
  - 12

before_script:
  - psql -c 'create database  avodb;' -U postgres
  - psql -U postgres -d avodb -a -f ./sql/tables.sql

services:
  - postgresql